version: "3.9"
services:
  dd-agent:
    image: "gcr.io/datadoghq/agent:7"
    ports:
      - "8126/tcp"
    environment:
      DD_API_KEY: "d2a4a83e6025e18786c61af648bd289c"
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE: "name:todoapi-dd-agent-1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw 

  api:
    build: .
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - dd-agent
    environment:
      DD_AGENT_HOST: "dd-agent"
      DD_TRACE_AGENT_PORT: 8126
      DD_ENV: "local"
      DD_VERSION: "20220601"
      # - - - - - - -
      DD_RUNTIME_METRICS_ENABLED: "true"
      DD_LOGS_INJECTION: "true"
      CORECLR_ENABLE_PROFILING: "1"
      CORECLR_PROFILER: "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}"
      CORECLR_PROFILER_PATH: "/opt/datadog/Datadog.Trace.ClrProfiler.Native.so"
      DD_DOTNET_TRACER_HOME: "/opt/datadog"
